# Generated by Django 5.2.14 on 2026-05-25 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_comment_id_alter_follow_id_alter_genre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='catalog.genre', verbose_name='Жанр'),
        ),
    ]
