# Generated by Django 6.0.5 on 2026-05-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_track_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/', verbose_name='Шапка профиля'),
        ),
    ]
