# Generated by Django 6.0.5 on 2026-05-31 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_profile_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AddField(
            model_name='track',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Лайкнувшие пользователи'),
        ),
        migrations.AddField(
            model_name='track',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('track', 'user')},
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
